# Generated by Django 4.0.2 on 2022-02-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_student', models.BooleanField()),
                ('student_id', models.TextField(max_length=30)),
                ('course_name', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=100)),
            ],
        ),
    ]
