# Generated by Django 4.0.2 on 2022-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
