# Generated by Django 3.2.9 on 2022-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_participant_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('is_student', models.BooleanField(blank=True, null=True)),
                ('student_id', models.TextField(blank=True, max_length=30, null=True)),
                ('course_name', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
